Add the feature if the user enters a wrong PIN then he can try it again.

diff --git a/scencrypt-hook b/scencrypt-hook
--- a/scencrypt-hook
+++ b/scencrypt-hook
@@ -1,16 +1,35 @@
 #!/usr/bin/ash
 
 card_status() {
-    /usr/bin/gpg --homedir "/etc/initcpio/gpg" --card-status --no-tty >/dev/null 2>&1
+    /usr/bin/gpg --homedir "/etc/initcpio/gpg" --card-status --no-tty \
+        >/dev/null 2>&1
     return $?
 }
 
 decrypt_file() {
     local input="$1"
     local output="${2:--}"
-    /usr/bin/gpg --homedir "/etc/initcpio/gpg" -o "${output}" --decrypt "${input}" \
-        0</dev/console 1>/dev/console 2>/dev/console
-    return $?
+    local status_file="/etc/initcpio/status"
+    local again=1
+    while [ $again -eq 1 ]; do
+        /usr/bin/gpg --homedir "/etc/initcpio/gpg" \
+            --status-file "$status_file" \
+            -o "${output}" --decrypt "${input}" \
+            0</dev/console 1>/dev/console 2>/dev/console
+        local status=$?
+        if [ "$status" -eq 0 ]; then
+            again=0
+        else
+            grep "^\[GNUPG:\] ERROR pkdecrypt_failed 100663383$" "$status_file" 
+            if [ $? -eq 0 ]; then
+                again=1
+            else
+                again=0
+            fi
+        fi
+        echo -n "" > "$status_file"
+    done
+return $status
 }
 
 retry() {
@@ -71,8 +90,8 @@ EOF
             test -d /.gnupg || mkdir -p /.gnupg
             chmod -R go-rwx /.gnupg /etc/initcpio/gpg
 
-            # store the key at a known path. this allows the same key to be used
-            # for multiple disks and only have to decrypt once.
+            # store the key at a known path. this allows the same key to be 
+            # used for multiple disks and only have to decrypt once.
             key_dest_path=/etc/initcpio/gpg/key_${key_file//\//S}
 
             # only attempt decryption if the keypath doesn't exist.
@@ -81,9 +100,10 @@ EOF
             else
                 # we need to decrypt.
 
-                # test communication with card - this is also needed for decryption
-                # to work at all
-                retry 60 "Waiting for the smartcard to be inserted (or press enter to falling back to passphrase)" card_status
+                # test communication with card - this is also needed for 
+                # decryption to work at all
+                retry 60 "Waiting for the smartcard to be inserted
+(or press enter to falling back to passphrase)" card_status
 
                 # now attempt to decrypt
                 if decrypt_file "${key_file}" "${key_dest_path}"; then
@@ -123,12 +143,16 @@ EOF
 
                 # open device
                 if [ -n "$key_file" ]; then
-                    if ! eval cryptsetup luksOpen --key-file="${key_file}" $luksoptions "${resolved}" "${mapped_name}"; then
-                        echo "WARNING: Failed to luksOpen crypto device ${device_path}"
+                    if ! eval cryptsetup luksOpen --key-file="${key_file}" \
+                        $luksoptions "${resolved}" "${mapped_name}"; then
+                        echo "WARNING: Failed to luksOpen crypto device" \
+                            ${device_path}
                     fi
                 else
-                    if ! eval cryptsetup luksOpen $luksoptions "${resolved}" "${mapped_name}"; then
-                        echo "WARNING: Failed to luksOpen crypto device ${device_path}"
+                    if ! eval cryptsetup luksOpen $luksoptions "${resolved}" \
+                        "${mapped_name}"; then
+                        echo "WARNING: Failed to luksOpen crypto device" \
+                            ${device_path}
                     fi
                 fi
             else
@@ -142,7 +166,8 @@ EOF
     done
     IFS="$IFS_BACKUP"
 
-    /usr/bin/gpg-connect-agent --homedir "/etc/initcpio/gpg" KILLAGENT /bye >/dev/null 2>&1
+    /usr/bin/gpg-connect-agent --homedir "/etc/initcpio/gpg" KILLAGENT /bye \
+        >/dev/null 2>&1
     rm -rf /etc/initcpio/gpg
 }
 
